CC=rmcc

all: longestLine ex1-16 ex1-17 ex1-18 ex1-19

longestLine: longestLine.c
	$(CC) -o longestLine longestLine.c
ex1-16: ex1-16.c
	$(CC) -o ex1-16 ex1-16.c
ex1-17: ex1-17.c
	$(CC) -o ex1-17 ex1-17.c
ex1-18: ex1-18.c
	$(CC) -o ex1-18 ex1-18.c
ex1-19: ex1-19.c
	$(CC) -o ex1-19 ex1-19.c
